name: Build, test, and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: MoviesMadeEasy
  AZURE_WEBAPP_PACKAGE_PATH: './publish_output'
  DOTNET_VERSION: '8.0.x'

on:
  push:
    branches: [ "dash_movie_modal" ] 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore .NET dependencies
        run: dotnet restore MoviesMadeEasyProject/MoviesMadeEasy/MoviesMadeEasy.csproj

      - name: Install npm packages
        run: npm install

      - name: Build with dotnet
        run: dotnet build MoviesMadeEasyProject/MoviesMadeEasy/MoviesMadeEasy.csproj --configuration Release

      - name: Run backend unit tests (NUnit)
        run: dotnet test MoviesMadeEasyProject/Tests_Unit/Tests_Unit.csproj --verbosity normal

      - name: Install Chrome & ChromeDriver
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          sudo apt-get install -y jq
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3)
          echo "Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
            jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform=="linux64") | .url')
          wget -O chromedriver.zip "$CHROMEDRIVER_URL"
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Create CI Program and publish directly
        run: |
          # Create temporary directory for CI build
          mkdir -p ci_build
          
          # Copy entire project excluding Program.cs
          cp -r MoviesMadeEasyProject ci_build/
          
          # Create modified Program.cs for CI
          cat > ci_build/MoviesMadeEasyProject/MoviesMadeEasy/Program.cs << 'EOL'
          using MoviesMadeEasy.DAL.Abstract;
          using MoviesMadeEasy.DAL.Concrete;
          using Microsoft.EntityFrameworkCore;
          using MoviesMadeEasy.Models;
          using MoviesMadeEasy.Data;
          using Microsoft.AspNetCore.Identity;
          using Microsoft.AspNetCore.Authentication;
          using Microsoft.Extensions.Logging;
          using Microsoft.Extensions.DependencyInjection;
          using Polly;
          using Polly.Extensions.Http;
          using Microsoft.AspNetCore.Session;

          var builder = WebApplication.CreateBuilder(args);

          builder.Logging.ClearProviders();
          builder.Logging.AddConsole();
          builder.Logging.AddDebug();
          builder.Logging.SetMinimumLevel(LogLevel.Information);

          // For CI/CD environment, add API keys directly
          builder.Configuration["OpenAI_ApiKey"] = "sk-dummy-key-for-testing";
          builder.Configuration["TMDBApiKey"] = "dummy-key-for-testing";
          builder.Configuration["RapidApiKey"] = "dummy-rapid-api-key-for-testing";
          builder.Configuration["OpenAI_Model"] = "gpt-3.5-turbo";

          if (builder.Environment.IsDevelopment())
          {
              builder.Configuration.AddUserSecrets<Program>();
          }

          if (builder.Environment.IsDevelopment())
          {
              builder.Services.AddControllersWithViews().AddRazorRuntimeCompilation();
              builder.Services.AddRazorPages().AddRazorRuntimeCompilation();
          }
          else
          {
              builder.Services.AddControllersWithViews();
          }

          builder.Services.AddHttpClient<IOpenAIService, OpenAIService>()
              .AddPolicyHandler(Policy<HttpResponseMessage>
                  .Handle<HttpRequestException>()
                  .OrResult(x => (int)x.StatusCode == 429)
                  .WaitAndRetryAsync(3, retryAttempt =>
                      TimeSpan.FromSeconds(Math.Pow(2, retryAttempt))));
                      
          builder.Services.AddHttpClient<IMovieService, MovieService>();
          builder.Services.AddScoped<IMovieService, MovieService>(provider =>
          {
              var httpClient = provider.GetRequiredService<HttpClient>();
              var configuration = provider.GetRequiredService<IConfiguration>();
              return new MovieService(httpClient, configuration);
          });

          builder.Services.AddScoped<ISubscriptionRepository, SubscriptionRepository>();
          builder.Services.AddScoped<IUserRepository, UserRepository>();
          builder.Services.AddScoped<IOpenAIService, OpenAIService>();
          builder.Services.AddScoped<ITitleRepository, TitleRepository>();
          
          Console.WriteLine("Using in-memory database for CI/CD");
          builder.Services.AddDbContext<UserDbContext>(options =>
              options.UseInMemoryDatabase("TestDb"));

          builder.Services.AddDbContext<IdentityDbContext>(options =>
              options.UseInMemoryDatabase("TestAuthDb"));

          builder.Services.AddScoped<DbContext>(sp => sp.GetRequiredService<UserDbContext>());

          builder.Services.AddDefaultIdentity<IdentityUser>(options =>
          {
              options.SignIn.RequireConfirmedAccount = false;
              options.User.RequireUniqueEmail = true;
          })
          .AddEntityFrameworkStores<IdentityDbContext>();

          builder.Services.AddRazorPages();

          builder.Services.AddDistributedMemoryCache();
          builder.Services.AddSession(options =>
          {
              options.IdleTimeout = TimeSpan.FromMinutes(30);
              options.Cookie.HttpOnly = true;
              options.Cookie.IsEssential = true;
          });

          var app = builder.Build();

          if (!app.Environment.IsDevelopment())
          {
              app.UseExceptionHandler("/Home/Error");
              app.UseHsts();
          }

          using (var scope = app.Services.CreateScope())
          {
              var services = scope.ServiceProvider;
              try
              {
                  SeedData.InitializeAsync(services).Wait();
                  Console.WriteLine("Database seeded successfully");
              }
              catch (Exception ex)
              {
                  Console.WriteLine($"An error occurred seeding the DB: {ex.Message}");
                  Console.WriteLine(ex.StackTrace);
              }
          }

          app.UseHttpsRedirection();
          app.UseStaticFiles();
          app.UseRouting();
          app.UseSession();
          app.UseAuthentication();
          app.UseAuthorization();

          app.MapControllerRoute(
              name: "default",
              pattern: "{controller=Home}/{action=Index}/{id?}");

          app.MapRazorPages();

          app.Run();
          EOL
          
          # Create CI appsettings.json
          cat > ci_build/MoviesMadeEasyProject/MoviesMadeEasy/appsettings.json << 'EOL'
          {
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*",
            "OpenAI_ApiKey": "sk-dummy-key-for-testing",
            "TMDBApiKey": "dummy-key-for-testing",
            "RapidApiKey": "dummy-rapid-api-key-for-testing",
            "OpenAI_Model": "gpt-3.5-turbo"
          }
          EOL
          
          # Build from the CI directory
          dotnet publish ci_build/MoviesMadeEasyProject/MoviesMadeEasy/MoviesMadeEasy.csproj --configuration Release --output ./publish_output
          
          # Copy the CI config to output
          cp ci_build/MoviesMadeEasyProject/MoviesMadeEasy/appsettings.json ./publish_output/appsettings.json

      - name: Run web app with detailed logging
        run: |
          cd ./publish_output
          nohup dotnet MoviesMadeEasy.dll --urls http://localhost:5000 > app.log 2>&1 &
          
          # Wait for app to initialize
          echo "Waiting 10 seconds for app to start..."
          sleep 10
          
          # Check if app is responding
          echo "Checking if app is responding..."
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
          echo "App response code: $RESPONSE"
          
          # Display logs regardless of status
          echo "=== Application Logs ==="
          cat app.log
          echo "======================="
          
          if [[ "$RESPONSE" != "200" ]]; then
            echo "App failed to start properly. Exiting."
            exit 1
          fi

      - name: Run BDD tests (NUnit + Selenium)
        run: dotnet test MoviesMadeEasyProject/MyBddProject.Tests/MyBddProject.Tests.csproj --verbosity normal

      - name: Run frontend tests (Jest)
        run: npm run test

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish_output

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}